---
title: "Playground"
author: "Frances Hung"
date: "10/21/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE)
```

## Playground


```{r}
require(gtrendsR)
require(ggplot2)
require(dplyr)
require(ggmap)
```

## Making Dataframes

This gives us a master dataframe of search frequencies of “depression” over the past 12 months in the US which relate for sure to mental health. We can take different dataframes using "$": see the dataframe for details.

```{r}
trend<-gtrends("suicide",c("US"),time="today 12-m")
trend$interest_by_region
```

For example, this gives us search frequencies by cities in CA in the U.S.

```{r}
cities_longlat<-read.csv("cal_cities.csv",header=TRUE) %>% select(c(location,Latitude,Longitude))
cities_dep<-gtrends("depression",c("US-CA"),time="today 12-m")$interest_by_city
cities_dep<-cities_dep %>% inner_join(cities_longlat,by="location")

write.csv(cities_dep,file="cities_top49.csv")
```

This plots cities_dep.

```{r}
ggplot(cities_dep,aes(x=reorder(location,hits),y=hits))+geom_bar(stat="identity")+theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
```{r}

for (i in 1:length(cities_dep$location)) {
  place=geocode(cities_dep$location[i],output="latlon",source="dsk")
  cities_dep$lat[i]=as.numeric(place[1])
  cities_dep$lon[i]=as.numeric(place[2])
}
```

```{r}
center=as.numeric(geocode("United States",source="dsk"))
mappy<-get_map(c(-119.4179,36.7783),zoom=6,scale=2,maptype = "terrain",source="google")
p=ggmap(mappy,extent="device",ylab="Latitude",xlab="Longitude")
p=p+geom_point(data=cities_dep,aes(x=lat,y=lon),size=(cities_dep$hits/50)^2)
p
```

```{r}
suis<-read.csv(file="death.csv",header=TRUE)
suis %>% filter(Causes.of.Death=="SUI") %>% filter(Year==2010)
```

